Fix recursive CHMOD issue
keycdn/cache-enabler pull request #317
Opened 2022-09-11 16:07 UTC by robwoodgate

Fixes #316

2022-09-12 10:34 UTC, robwoodgate commented
@coreykn - this is a pretty urgent fix that prevents CE crashing websites (esp on PHP-FPM)

2022-09-12 10:45 UTC, futtta commented
@svenba I've seen my site crashing as well when using keycdn on php-fpm. can't say if this was the root cause, but it seems likely?

2022-09-12 13:03 UTC, robwoodgate commented
> @svenba I've seen my site crashing as well when using keycdn on php-fpm. can't say if this was the root cause, but it seems likely?

Took me many days of head-scratching and site outages to figure out... and still not entirely sure how it gets triggered, but after adding lots of error logging and debug_backtraces, I narrowed it down to the chain of events I detailed in #316. The PHP-FPM crash occurs because the permissions of the socket are changed by the recursive chmod.

2022-09-14 08:31 UTC, svenba commented
Thank you for the pull request! I'm going to review this in the next couple of days

2022-09-19 14:32 UTC, svenba requested changes

2022-09-19 15:00 UTC, robwoodgate commented on inc/cache_enabler_disk.class.php
> +            return CACHE_ENABLER_CACHE_DIR;
Hi @svenba - have you read through the related issue #316 ? This explains the reason why and how the result of this method is related to the recursive chmod.

In summary, the cache_dir is made up of three parts: CACHE_ENABLER_CACHE_DIR / $url_host  /  $url_path

It is not correct to return nothing if the url_host isn't specified. By returning CACHE_ENABLER_CACHE_DIR, at least the method is containing any subsequent actions to that folder.

In other words, it "fails safe" if $url_host isn't found.

2022-09-19 15:23 UTC, svenba approved these changes

2022-09-19 15:24 UTC, merged